# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_camera.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1338, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 651, 581))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_camera = QtWidgets.QLabel(self.groupBox)
        self.label_camera.setMinimumSize(QtCore.QSize(0, 574))
        self.label_camera.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_camera.setText("")
        self.label_camera.setScaledContents(True)
        self.label_camera.setObjectName("label_camera")
        self.verticalLayout_3.addWidget(self.label_camera)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_open = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_open.setObjectName("pushButton_open")
        self.horizontalLayout.addWidget(self.pushButton_open)
        self.pushButton_close = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.pushButton_takephoto = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_takephoto.setObjectName("pushButton_takephoto")
        self.horizontalLayout.addWidget(self.pushButton_takephoto)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(670, 440, 651, 271))
        self.tabWidget.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_canny = QtWidgets.QWidget()
        self.tab_canny.setObjectName("tab_canny")
        self.horizontalSlider_canny_max = QtWidgets.QSlider(self.tab_canny)
        self.horizontalSlider_canny_max.setGeometry(QtCore.QRect(130, 80, 411, 16))
        self.horizontalSlider_canny_max.setMaximum(255)
        self.horizontalSlider_canny_max.setProperty("value", 0)
        self.horizontalSlider_canny_max.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_canny_max.setObjectName("horizontalSlider_canny_max")
        self.horizontalSlider_canny_min = QtWidgets.QSlider(self.tab_canny)
        self.horizontalSlider_canny_min.setGeometry(QtCore.QRect(130, 120, 411, 16))
        self.horizontalSlider_canny_min.setMaximum(255)
        self.horizontalSlider_canny_min.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_canny_min.setObjectName("horizontalSlider_canny_min")
        self.label_canny_max = QtWidgets.QLabel(self.tab_canny)
        self.label_canny_max.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_canny_max.setObjectName("label_canny_max")
        self.label_canny_min = QtWidgets.QLabel(self.tab_canny)
        self.label_canny_min.setGeometry(QtCore.QRect(10, 110, 111, 21))
        self.label_canny_min.setObjectName("label_canny_min")
        self.checkBox_canny_use = QtWidgets.QCheckBox(self.tab_canny)
        self.checkBox_canny_use.setGeometry(QtCore.QRect(570, 100, 61, 20))
        self.checkBox_canny_use.setObjectName("checkBox_canny_use")
        self.tabWidget.addTab(self.tab_canny, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 610, 651, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(30, 40, 101, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 40, 91, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(260, 40, 101, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(390, 40, 101, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(520, 40, 101, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(670, 10, 641, 411))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_image = QtWidgets.QLabel(self.groupBox_3)
        self.label_image.setGeometry(QtCore.QRect(20, 40, 491, 361))
        self.label_image.setMinimumSize(QtCore.QSize(0, 340))
        self.label_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image.setText("")
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.pushButton_openPic = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_openPic.setGeometry(QtCore.QRect(520, 40, 111, 26))
        self.pushButton_openPic.setObjectName("pushButton_openPic")
        self.pushButton_savePic = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_savePic.setGeometry(QtCore.QRect(520, 370, 101, 26))
        self.pushButton_savePic.setObjectName("pushButton_savePic")
        self.label_imageSize = QtWidgets.QLabel(self.groupBox_3)
        self.label_imageSize.setGeometry(QtCore.QRect(30, 50, 121, 21))
        self.label_imageSize.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_imageSize.setText("")
        self.label_imageSize.setObjectName("label_imageSize")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1338, 23))
        self.menubar.setStyleSheet("")
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionXuanzhuan = QtWidgets.QAction(MainWindow)
        self.actionXuanzhuan.setObjectName("actionXuanzhuan")
        self.actionXuanzhuan_2 = QtWidgets.QAction(MainWindow)
        self.actionXuanzhuan_2.setObjectName("actionXuanzhuan_2")
        self.actionRed = QtWidgets.QAction(MainWindow)
        self.actionRed.setObjectName("actionRed")
        self.actionGreen = QtWidgets.QAction(MainWindow)
        self.actionGreen.setObjectName("actionGreen")
        self.actionBlue = QtWidgets.QAction(MainWindow)
        self.actionBlue.setObjectName("actionBlue")
        self.actionOpenCv = QtWidgets.QAction(MainWindow)
        self.actionOpenCv.setObjectName("actionOpenCv")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionRgb = QtWidgets.QAction(MainWindow)
        self.actionRgb.setObjectName("actionRgb")
        self.actionPingyi = QtWidgets.QAction(MainWindow)
        self.actionPingyi.setObjectName("actionPingyi")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.actionYasuo = QtWidgets.QAction(MainWindow)
        self.actionYasuo.setObjectName("actionYasuo")
        self.actionJieya = QtWidgets.QAction(MainWindow)
        self.actionJieya.setObjectName("actionJieya")
        self.menu.addAction(self.actionXuanzhuan)
        self.menu.addAction(self.actionXuanzhuan_2)
        self.menu.addAction(self.actionPingyi)
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.actionRed)
        self.menu_2.addAction(self.actionGreen)
        self.menu_2.addAction(self.actionBlue)
        self.menu_2.addAction(self.actionRgb)
        self.menu_3.addAction(self.actionOpenCv)
        self.menu_3.addAction(self.action)
        self.menu_3.addAction(self.action_2)
        self.menu_4.addAction(self.actionYasuo)
        self.menu_4.addAction(self.actionJieya)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenCv图像处理教学演示系统V1.0"))
        self.groupBox.setTitle(_translate("MainWindow", "摄像头"))
        self.pushButton_open.setText(_translate("MainWindow", "打开摄像头"))
        self.pushButton_close.setText(_translate("MainWindow", "关闭摄像头"))
        self.pushButton_takephoto.setText(_translate("MainWindow", "拍照"))
        self.label_canny_max.setText(_translate("MainWindow", "最高阈值:0/255"))
        self.label_canny_min.setText(_translate("MainWindow", "最低阈值:0/255"))
        self.checkBox_canny_use.setText(_translate("MainWindow", "启用"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_canny), _translate("MainWindow", "边缘检测"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "平滑图像"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "几何变换"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "压缩解压"))
        self.groupBox_2.setTitle(_translate("MainWindow", "高级设置"))
        self.radioButton.setText(_translate("MainWindow", "原始图像"))
        self.radioButton_2.setText(_translate("MainWindow", "边缘检测"))
        self.radioButton_3.setText(_translate("MainWindow", "原始图像"))
        self.radioButton_4.setText(_translate("MainWindow", "原始图像"))
        self.radioButton_5.setText(_translate("MainWindow", "原始图像"))
        self.groupBox_3.setTitle(_translate("MainWindow", "图片"))
        self.pushButton_openPic.setText(_translate("MainWindow", "打开图片"))
        self.pushButton_savePic.setText(_translate("MainWindow", "保存图片"))
        self.menu.setTitle(_translate("MainWindow", "几何变换"))
        self.menu_2.setTitle(_translate("MainWindow", "颜色空间转换"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.menu_4.setTitle(_translate("MainWindow", "压缩解压"))
        self.actionXuanzhuan.setText(_translate("MainWindow", "翻转"))
        self.actionXuanzhuan_2.setText(_translate("MainWindow", "旋转"))
        self.actionRed.setText(_translate("MainWindow", "追踪红色"))
        self.actionGreen.setText(_translate("MainWindow", "追踪绿色"))
        self.actionBlue.setText(_translate("MainWindow", "追踪蓝色"))
        self.actionOpenCv.setText(_translate("MainWindow", "OpenCv功能接口"))
        self.action.setText(_translate("MainWindow", "软件使用说明"))
        self.action_2.setText(_translate("MainWindow", "版权说明"))
        self.actionRgb.setText(_translate("MainWindow", "追踪红绿蓝"))
        self.actionPingyi.setText(_translate("MainWindow", "平移"))
        self.action_3.setText(_translate("MainWindow", "缩放"))
        self.actionYasuo.setText(_translate("MainWindow", "压缩图片"))
        self.actionJieya.setText(_translate("MainWindow", "解压图片"))

